In [1]:
import pandas as pd
import numpy as np

In [2]:
# Reading the converion file for FIPS CODE TO State
FIP_State = pd.read_csv("fipstostate.csv")
FIP_State.head()

   fips state_abbr
0     1         AL
1     2         AK
2     4         AZ
3     5         AR
4     6         CA

In [3]:
# Reading the SAS file
DF=pd.read_sas("../LLCP2012.XPT")

In [4]:
# Rxtracting the required columns to the new DF
NDF=DF[["IDATE","_STATE", "SEX", "_AGEG5YR", "_PRACE", "EMPLOY","MSCODE", "MENTHLTH", "_BMI5CAT",
        "_RFHLTH","_HCVU651","SLEPTIME","CVDINFR4","CVDCRHD4","CVDSTRK3", "ASTHNOW","CHCSCNCR", 
        "CHCOCNCR","CHCCOPD1","_DRDXAR1","ADDEPEV2", "CHCKIDNY", "DIABETE3","PREGNANT", "_TOTINDA",
        "QLMENTL2","QLSTRES2","_RFSMOK3", "_RFDRHV4", "EMTSUPRT", "LSATISFY","_INCOMG"]]

In [5]:
# Re-naming the _STATE to fips for merging the FIPS DF and New DF
NDF = NDF.rename(columns={"_STATE":"fips"})
NDF = NDF.merge(FIP_State,on="fips")
# Dropping the fips column as it is not required further
NDF.drop(["fips"],axis=1,inplace=True)

In [6]:
# Convert date from byte to string
NDF["IDATE"] = NDF["IDATE"].str.decode("utf-8")

# Converting the column values to sensible values as per the Codebook from CDC
NDF["SEX"] = NDF["SEX"].replace({1.0:"M",2.0:"F",None:"NA"})

NDF["MSCODE"] = NDF["MSCODE"].replace({1.0:"Urban", 2.0:"Urban", 3.0:"Urban", 4.0:"Urban", 5.0:"Rural", None:"Rural"})
NDF["_AGEG5YR"] = NDF["_AGEG5YR"].replace({1.0:"18-24",2.0:"25-29",3.0:"30-34",4.0:"35-39",5.0:"40-44",
                                                  6.0:"45-49",7.0:"50-54",8.0:"55-59",9.0:"60-64",10.0:"65-69",
                                                  11.0:"70-74",12.0:"75-79",13.0:"80+",14.0:"NA", None:"NA"})
NDF["_PRACE"] = NDF["_PRACE"].replace({1.0:"White",2.0:"Black or African American",3.0:"Asian",
                                               4.0:"Native Hawaiian or Other Pacific Islander",
                                               5.0:"American Indian, Alaska Native",6.0:"Other",
                                               7.0:"nan", 8.0:"Multiracial",77.0:"NA", 99.0:"NA", None:"NA"})
NDF["EMPLOY"] = NDF["EMPLOY"].replace({1.0:"Employed", 2.0:"Self-Employed", 3.0:"Out of work",
                                               4.0:"Out of work", 5.0:"Homemaker", 6.0:"Student",
                                               7.0:"Retired", 8.0:"Unable to work", 9.0:"NA", None:"NA"})
NDF["MENTHLTH"] = NDF["MENTHLTH"].replace({88:0,77:0 ,99:0, None:0})
NDF["_RFHLTH"] = NDF["_RFHLTH"].replace({1:"Good",2:"Poor",9:"NA", None:"NA"})
NDF["_HCVU651"] = NDF["_HCVU651"].replace({1:"Y", 2:"N", 9:"NA", None:"NA"})
NDF["CVDINFR4"]= NDF["CVDINFR4"].replace({1:"Y", 2:"N", 7:None, 9:None})
NDF["CVDCRHD4"] = NDF["CVDCRHD4"].replace({1:"Y", 2:"N", 7:None, 9:None})
NDF["CVDSTRK3"] = NDF["CVDSTRK3"].replace({1:"Y", 2:"N", 7:None, 9:None})
NDF["ASTHNOW"] = NDF["ASTHNOW"].replace({1:"Y", 2:"N", 7:None, 9:None})
NDF["CHCSCNCR"] = NDF["CHCSCNCR"].replace({1:"Y", 2:"N", 7:None, 9: None})
NDF["CHCOCNCR"] = NDF["CHCOCNCR"].replace({1:"Y", 2:"N", 7:None, 9: None})
NDF["CHCCOPD1"] = NDF["CHCCOPD1"].replace({1:"Y", 2:"N", 7:None, 9: None})
NDF["_DRDXAR1"] = NDF["_DRDXAR1"].replace({1:"Y", 2:"N"})
NDF["ADDEPEV2"] = NDF["ADDEPEV2"].replace({1:"Y", 2:"N", 7:"NA", 9: "NA", None:"NA"})
NDF["CHCKIDNY"] = NDF["CHCKIDNY"].replace({1:"Y", 2:"N", 7:None, 9: None})
NDF["DIABETE3"] = NDF["DIABETE3"].replace({1:"Y", 2:"N", 3:"N", 4:"N", 7:None, 9: None})
NDF["PREGNANT"] = NDF["PREGNANT"].replace({1:"Y", 2:"N", 7:"NA", 9: "NA", None:"NA"})
NDF["QLSTRES2"] = NDF["QLSTRES2"].replace({88:0,77:0,99:0,None:0})
NDF["QLMENTL2"] = NDF["QLMENTL2"].replace({88:0,77:0,99:0,None:0})
NDF["_RFSMOK3"] = NDF["_RFSMOK3"].replace({1:"Non-Smoker", 2:"Smoker", 9:"NA"})
NDF["_RFDRHV4"] = NDF["_RFDRHV4"].replace({1:"Non-Alcoholic", 2:"Alcoholic", 9:"NA"})
NDF["_TOTINDA"] = NDF["_TOTINDA"].replace({1:"Y", 2:"N", 9:"NA", None:"NA"})
NDF["_BMI5CAT"] = NDF["_BMI5CAT"].replace({1:"Underweight", 2:"Normal", 3:"Overweight", 4:"Obese", None:"NA"})
NDF["_INCOMG"] = NDF["_INCOMG"].replace({1:"<15000", 2:"15000-<25000", 3: "25000-<35000", 4:"35000-<50000",
                                        5:"50000+",9:"NA"})
NDF["EMTSUPRT"] = NDF["EMTSUPRT"].replace({7:"NA", 9:"NA", None: "NA"})
NDF["LSATISFY"] = NDF["LSATISFY"].replace({1:"Satisfied", 2:"Satisfied", 3:"Not-Satisfied", 4:"Not-Satisfied", 7:"NA", 9:"NA", None:"NA"})

# Renaming the columns
NDF = NDF.rename(columns={"SEX": "Gender",
                          "DATE": "Date",
                          "_AGEG5YR":"Age_Range",
                          "_PRACE":"Race",
                          "EMPLOY":"Employment_Status",
                          "_INCOMG": "Income",
                          "MENTHLTH":"Mental_Health_Factor", 
                          "_RFHLTH": "General_Health",
                          "_HCVU651":"Health_Coverage",
                          "ADDEPEV2":"Chronic_Depression",
                          "PREGNANT": "Pregnant",
                          "QLMENTL2": "Depressed_Days",
                          "QLSTRES2":"Stress_Days", 
                          "_RFSMOK3":"Smoke_Frequency",
                          "_RFDRHV4":"Alcohol_Frequency",
                          "SLEPTIME":"Sleep_Hours",
                          "state_abbr":"State",
                          "IDATE":"Date",
                          "_TOTINDA":"Physical_Activity",
                          "_BMI5CAT":"BMI",
                          "MSCODE":"MetroStatusCode",
                          "EMTSUPRT" : "EmotionalSupport_Availability", 
                          "LSATISFY" : "LifeSatisfaction_Level"})

# Arranging the columns in the Data Frame
NDF = NDF[["Date","State","Gender","Age_Range","BMI","Race","Employment_Status","Income","MetroStatusCode",
                   "General_Health","Mental_Health_Factor","Health_Coverage","Physical_Activity","Chronic_Depression",
                   "Pregnant","Depressed_Days","Stress_Days","Smoke_Frequency", "Alcohol_Frequency", "Sleep_Hours",
                   "EmotionalSupport_Availability","LifeSatisfaction_Level","CVDINFR4","CVDCRHD4","CVDSTRK3", 
                   "ASTHNOW","CHCSCNCR", "CHCOCNCR","CHCCOPD1","_DRDXAR1", "CHCKIDNY", "DIABETE3"]]


NDF.head()

,Date,State,Gender,Age_Range,BMI,Race,Employment_Status,Income,MetroStatusCode,General_Health,...,CVDINFR4,CVDCRHD4,CVDSTRK3,ASTHNOW,CHCSCNCR,CHCOCNCR,CHCCOPD1,_DRDXAR1,CHCKIDNY,DIABETE3
0,02162012,AL,M,60-64,Overweight,White,Retired,35000-<50000,Rural,Good,...,N,N,N,NaN,N,N,N,Y,N,N
1,01052012,AL,M,50-54,Overweight,White,Employed,50000+,Urban,Good,...,N,N,N,NaN,N,N,N,N,N,N
2,01032012,AL,F,65-69,Obese,Black or African American,Retired,NA,Urban,Poor,...,N,Y,N,Y,N,N,Y,Y,Y,N
3,01192012,AL,F,70-74,Normal,White,Unable to work,15000-<25000,Urban,Good,...,N,N,N,NaN,Y,N,N,N,N,N
4,01062012,AL,F,60-64,Obese,White,Retired,NA,Urban,Poor,...,N,N,N,NaN,N,N,N,Y,N,Y

In [7]:
# Creating a new empty column for Chronic Disease computation
NDF["Chronic_Disease"]=""

# For each record in the data frame based on the values for existing diseases adding a point to the final value
for index, row in NDF.iterrows():
    chron_dep=0
    if row["CVDINFR4"]=="Y":
        chron_dep+=1
    else:
        chron_dep+=0
        
    if row["CVDCRHD4"]=="Y":
        chron_dep+=1
    else:
        chron_dep+=0
    
    if row["CVDSTRK3"]=="Y":
        chron_dep+=1
    else:
        chron_dep+=0
    
    if row["ASTHNOW"]=="Y":
        chron_dep+=1
    else:
        chron_dep+=0
    
    if row["CHCSCNCR"]=="Y":
        chron_dep+=1
    else:
        chron_dep+=0
    
    if row["CHCOCNCR"]=="Y":
        chron_dep+=1
    else:
        chron_dep+=0
    
    if row["CHCCOPD1"]=="Y":
        chron_dep+=1
    else:
        chron_dep+=0
    
    if row["_DRDXAR1"]=="Y":
        chron_dep+=1
    else:
        chron_dep+=0
    
    if row["CHCKIDNY"]=="Y":
        chron_dep+=1
    else:
        chron_dep+=0
    
    if row["DIABETE3"]=="Y":
        chron_dep+=1
    else:
        chron_dep+=0
    
    # Setting the computated value to Chronic_Disease column
    NDF.set_value(index, "Chronic_Disease",chron_dep)

# Dropping the remaining columns as they are not required furthe
NDF.drop(["CVDINFR4","CVDCRHD4","CVDSTRK3","ASTHNOW","CHCSCNCR",
          "CHCOCNCR","CHCCOPD1","_DRDXAR1","CHCKIDNY","DIABETE3"],axis=1,inplace=True)

NDF.head()

,Date,State,Gender,Age_Range,BMI,Race,Employment_Status,Income,MetroStatusCode,General_Health,...,Chronic_Depression,Pregnant,Depressed_Days,Stress_Days,Smoke_Frequency,Alcohol_Frequency,Sleep_Hours,EmotionalSupport_Availability,LifeSatisfaction_Level,Chronic_Disease
0,02162012,AL,M,60-64,Overweight,White,Retired,35000-<50000,Rural,Good,...,N,NA,0.0,0.0,Non-Smoker,Non-Alcoholic,NaN,NA,NA,1
1,01052012,AL,M,50-54,Overweight,White,Employed,50000+,Urban,Good,...,N,NA,0.0,0.0,Non-Smoker,Non-Alcoholic,NaN,NA,NA,0
2,01032012,AL,F,65-69,Obese,Black or African American,Retired,NA,Urban,Poor,...,Y,NA,0.0,0.0,Non-Smoker,NA,NaN,NA,NA,5
3,01192012,AL,F,70-74,Normal,White,Unable to work,15000-<25000,Urban,Good,...,N,NA,0.0,0.0,Non-Smoker,Non-Alcoholic,NaN,NA,NA,1
4,01062012,AL,F,60-64,Obese,White,Retired,NA,Urban,Poor,...,N,NA,0.0,0.0,Non-Smoker,Non-Alcoholic,NaN,NA,NA,2

In [8]:
# A funtion to find a weighted variable based on various factors as the Mental Health Value
def CalculatedVariable(DF):
    
    # For each record in the dat
    for index,row in DF.iterrows():
        
        # Intializing the variables
        CalcVar=0
        TotalWght=0
        
        # Priority 1
        
        # For General Health 
        if row["General_Health"]=="Poor":
            CalcVar+=10
        else:
            CalcVar+=0
        
        # For Smokers
        if row["Smoke_Frequency"]=="Smoker":
            CalcVar+=10
        else:
            CalcVar+=0
        
        # For Alcoholics
        if row["Alcohol_Frequency"]=="Alcoholic":
            CalcVar+=10
        else:
            CalcVar+=0

        # For Sleeping disorders
        if row["Sleep_Hours"]<5 and row["Sleep_Hours"]>10:
            CalcVar+=10
        else:
            CalcVar+=0
        
        # For Obesity, Overweight and Underweight
        if row["BMI"]=="Obese":
            CalcVar+=10
        elif row["BMI"]=="Overweight":
            CalcVar+=8
        elif row["BMI"]=="Underweight":
            CalcVar+=8
        else:
            CalcVar+=0

        # For Physical Activity
        if row["Physical_Activity"]=="N":
            CalcVar+=10
        else:
            CalcVar+=0

        # For Chronic Disease
        # As there is already a existing value in the score of 10 adding that value to the Calculated Variable
        CalcVar+=row["Chronic_Disease"]

        # For Pregnancy
        if row["Pregnant"]=="Y":
            CalcVar+=10
        else:
            CalcVar+=0
    
    
        # Priority 2
        # For Income
        if row["Income"]=="<15000":
            CalcVar+=5
        elif row["Income"]=="15000-<25000":
            CalcVar+=4
        elif row["Income"]=="25000-<35000":
            CalcVar+=3
        elif row["Income"]=="35000-<50000":
            CalcVar+=2
        elif row["Income"]=="50000+":
            CalcVar+=1

        # Priority 3
        # For Emotional Support Availability
        if row["EmotionalSupport_Availability"]==1:
            CalcVar+=0.5
        elif row["EmotionalSupport_Availability"]==2:
            CalcVar+=1
        elif row["EmotionalSupport_Availability"]==3:
            CalcVar+=1.5
        elif row["EmotionalSupport_Availability"]==4:
            CalcVar+=2
        elif row["EmotionalSupport_Availability"]==5:
            CalcVar+=2.5
        # For Life Satisfaction Level
        if row["LifeSatisfaction_Level"]=="Not-Satisfied":
            CalcVar+=2.5
        else:
            CalcVar+=0
       
        # If the person has reported Chronic Depression
        if row["Chronic_Depression"]=="Y":
            chronic_dep=10
            # Converting the stress days(1-30) to a score of 10
            stress=row["Stress_Days"]*(1/3)
             # Converting the depressed days(1-30) to a score of 10
            depress=row["Depressed_Days"]*(1/3)
        else:
            # Converting the stress days(1-30) to a score of 10
            stress=row["Stress_Days"]*(1/3)
            # Converting the depressed days(1-30) to a score of 10
            depress=row["Depressed_Days"]*(1/3)
            chronic_dep=1
            
        # Calculating the average mental factor value
        avg_depr=(stress+depress+chronic_dep)*(2/3)
        
        # Checking if male or female and based on that converting the score to 100
        if row["Gender"]=="M":
            TotalWght=(CalcVar+avg_depr)*100/100
        else:
            TotalWght=(CalcVar+avg_depr)*100/110
    
        DF.set_value(index,"Calc_MentalHealth_Value",round(TotalWght,2))   
        
NDF["Calc_MentalHealth_Value"]=""
CalculatedVariable(NDF)

In [9]:
NDF.head()

,Date,State,Gender,Age_Range,BMI,Race,Employment_Status,Income,MetroStatusCode,General_Health,...,Pregnant,Depressed_Days,Stress_Days,Smoke_Frequency,Alcohol_Frequency,Sleep_Hours,EmotionalSupport_Availability,LifeSatisfaction_Level,Chronic_Disease,Calc_MentalHealth_Value
0,02162012,AL,M,60-64,Overweight,White,Retired,35000-<50000,Rural,Good,...,NA,0.0,0.0,Non-Smoker,Non-Alcoholic,NaN,NA,NA,1,21.67
1,01052012,AL,M,50-54,Overweight,White,Employed,50000+,Urban,Good,...,NA,0.0,0.0,Non-Smoker,Non-Alcoholic,NaN,NA,NA,0,9.67
2,01032012,AL,F,65-69,Obese,Black or African American,Retired,NA,Urban,Poor,...,NA,0.0,0.0,Non-Smoker,NA,NaN,NA,NA,5,37.88
3,01192012,AL,F,70-74,Normal,White,Unable to work,15000-<25000,Urban,Good,...,NA,0.0,0.0,Non-Smoker,Non-Alcoholic,NaN,NA,NA,1,14.24
4,01062012,AL,F,60-64,Obese,White,Retired,NA,Urban,Poor,...,NA,0.0,0.0,Non-Smoker,Non-Alcoholic,NaN,NA,NA,2,20.61

In [10]:
# Save the csv file
NDF.to_csv("../raw_data/output/MentalHealth2012.csv",index=False)